# Generated by Django 4.2.2 on 2023-06-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=1000, null=True)),
                ('canonical', models.CharField(blank=True, max_length=1000, null=True)),
                ('robot', models.CharField(blank=True, max_length=1000, null=True)),
                ('og_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('og_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og_image')),
            ],
        ),
    ]
