# Generated by Django 4.2.2 on 2023-07-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_blockplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockplace',
            name='block_status',
            field=models.BooleanField(default=False),
        ),
    ]
