# Generated by Django 4.2.2 on 2023-06-28 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('flag_img', models.ImageField(blank=True, null=True, upload_to='flag/')),
                ('allowed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CashPickup', 'Cash Pickup'), ('BankTransfer', 'Bank Transfer'), ('MobileTransfer', 'Mobile Transfer'), ('WallettoWalletTransfer', 'Wallet to Wallet Transfer')], max_length=300)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
                ('number', models.BigIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipent_country', to='homepage.country')),
            ],
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pickup_point', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickuppoint_country', to='homepage.country')),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
                ('number', models.BigIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200)),
                ('document_type', models.CharField(choices=[('Bank Account', 'Bank Account'), ('Benefits Card/ID', 'Benefits Card/ID'), ('Birth Certificate', 'Birth Certificate'), ('Business Registration/licence', 'Business Registration/licence'), ('Credit/debit card', 'Credit/debit card'), ('Driver licence', 'Driver licence'), ('Identity Card', 'Identity Card'), ('Passport', 'Passport'), ('Photo ID', 'Photo ID'), ('Security ID', 'Security ID'), ('Social Security ID', 'Social Security ID'), ('Student ID', 'Student ID'), ('Tax ID', 'Tax ID'), ('Other', 'Other')], max_length=200)),
                ('postal_address', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_country', to='homepage.country')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_customer', to='homepage.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currecy_rate', models.IntegerField()),
                ('conversion_rate', models.IntegerField()),
                ('commision_rate', models.IntegerField()),
                ('currecy_sign', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_country', to='homepage.country')),
            ],
        ),
    ]
