# Generated by Django 4.2.2 on 2023-06-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_customer_address_remove_customer_profil_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profil_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/customer/'),
        ),
    ]
