# Generated by Django 4.2.2 on 2023-06-30 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_recipient_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_customer', to='homepage.customer'),
        ),
    ]
