# Generated by Django 4.2.2 on 2023-06-18 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_customer_address_customer_profil_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='number',
        ),
    ]
