# Generated by Django 4.2.2 on 2023-06-29 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_country_created_at_country_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_customer', to='homepage.customer'),
        ),
    ]
