# Generated by Django 4.2.2 on 2023-07-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sent_money_to_us',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sent_to_client',
            field=models.BooleanField(default=False),
        ),
    ]
