# Generated by Django 4.2.2 on 2023-06-23 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_customer_city_customer_country_customer_mail_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupinterface',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='signup_video/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blog_category', to='homepage.category'),
        ),
        migrations.AlterField(
            model_name='signupinterface',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='login_image'),
        ),
    ]
