# Generated by Django 4.2.2 on 2023-06-25 16:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_signupinterface_video_alter_blog_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('feature', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.AlterField(
            model_name='logininterface',
            name='image',
            field=models.ImageField(upload_to='login_image/'),
        ),
        migrations.AlterField(
            model_name='signupinterface',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='signup_image/'),
        ),
    ]
