# Generated by Django 4.2.2 on 2023-06-26 03:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_feature_alter_logininterface_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose', ckeditor_uploader.fields.RichTextUploadingField()),
                ('hide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HomeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', ckeditor_uploader.fields.RichTextUploadingField()),
                ('hide', models.BooleanField(default=False)),
            ],
        ),
    ]
