# Generated by Django 4.2.2 on 2023-06-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_chooseus_homeservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home_image/'),
        ),
    ]
