# Generated by Django 4.2.2 on 2023-07-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_transaction_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_currency', to='homepage.currency')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_currency', to='homepage.customer')),
            ],
        ),
    ]
