# Generated by Django 4.2.2 on 2023-07-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_customer_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='footor',
            name='row',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='First', max_length=100),
        ),
    ]
