# Generated by Django 4.2.2 on 2023-07-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_kyc_expiry_date_kyc_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='business_registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
