# Generated by Django 4.2.2 on 2023-07-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_kyc_business_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='business_image',
            field=models.ImageField(blank=True, null=True, upload_to='document/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='document/'),
        ),
    ]
