# Generated by Django 4.2.2 on 2023-07-18 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_kyc_business_image_kyc_passport_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultcurrency',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_currency', to='homepage.currency'),
        ),
    ]
