# Generated by Django 4.2.2 on 2023-07-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_defaultnumber_emailsetting_smssetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='group',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Customer', 'Customer'), ('Recipient', 'Recipient'), ('All', 'All'), ('Individual', 'Individual')], default='Individual', max_length=200),
        ),
    ]
