# Generated by Django 4.2.2 on 2023-07-19 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_emaillist_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emaillist',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
