# Generated by Django 4.2.2 on 2023-07-20 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_rename_created_date_emaillist_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smslist',
            name='group',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Customer', 'Customer'), ('Recipient', 'Recipient'), ('All', 'All'), ('Individual', 'Individual')], default='Individual', max_length=200),
        ),
        migrations.AddField(
            model_name='smslist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
