# Generated by Django 4.2.2 on 2023-07-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_agent_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
