# Generated by Django 4.2.2 on 2023-07-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_feature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='blog',
            name='types',
            field=models.CharField(choices=[('News', 'News'), ('Blog', 'Blog')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
