# Generated by Django 4.2.2 on 2023-07-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0041_adminnotification_customernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customernotification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
