# Generated by Django 4.2.2 on 2023-07-25 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0048_customer_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCurrencyAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_receiving_currency', to='homepage.currency')),
                ('sending_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_sending_currency', to='homepage.currency')),
            ],
        ),
    ]
