# Generated by Django 4.2.2 on 2023-07-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0052_adminbankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='allowed',
        ),
    ]
