# Generated by Django 4.2.2 on 2023-07-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0054_loginlogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='kyc',
            name='licence_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='passport_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='registraion_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='country',
            field=models.CharField(max_length=200),
        ),
    ]
