# Generated by Django 4.2.2 on 2023-07-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0061_alter_currency_commision_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='commision_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='converting_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='received',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sent',
            field=models.IntegerField(default=0),
        ),
    ]
