# Generated by Django 4.2.2 on 2023-07-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0065_alter_ticketreply_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='zip_code',
        ),
    ]
