# Generated by Django 4.2.2 on 2023-08-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0072_alter_kyc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreply',
            name='description',
            field=models.TextField(),
        ),
    ]
