# Generated by Django 4.2.2 on 2023-08-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0077_alter_transactionnote_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslist',
            name='to',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
