# Generated by Django 4.2.2 on 2023-08-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0078_alter_smslist_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslist',
            name='from_sim',
        ),
    ]
