# Generated by Django 4.2.2 on 2023-08-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0079_remove_smslist_from_sim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslist',
            name='message',
            field=models.TextField(),
        ),
    ]
