# Generated by Django 4.2.2 on 2023-07-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('block', models.CharField(choices=[('Country', 'Country'), ('Region', 'Region'), ('City', 'City')], max_length=200)),
                ('block_status', models.BooleanField()),
            ],
        ),
    ]
