# Generated by Django 4.2.2 on 2023-07-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_transaction_sent_money_to_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='image',
            field=models.ImageField(default=1, upload_to='kyc_image'),
            preserve_default=False,
        ),
    ]
