# Generated by Django 4.2.2 on 2023-07-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_kyc_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='passport_issued_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
