# Generated by Django 4.2.2 on 2023-07-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_emaillist_created_date_emaillist_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillist',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='emaillist',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
