# Generated by Django 4.2.2 on 2023-07-20 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_remove_agent_added_by_remove_agent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_adder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='profil_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/agent/'),
        ),
        migrations.AddField(
            model_name='agent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
