# Generated by Django 4.2.2 on 2023-07-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_agent_city_agent_mail_address_agent_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_country', to='homepage.country'),
        ),
    ]
