# Generated by Django 4.2.2 on 2023-07-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_alter_agent_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='features_image/'),
        ),
    ]
