# Generated by Django 4.2.2 on 2023-07-22 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0033_supportticket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupportTicket',
            new_name='Ticket',
        ),
        migrations.CreateModel(
            name='SupportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='support_file/')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_support', to='homepage.ticket')),
            ],
        ),
    ]
