# Generated by Django 4.2.2 on 2023-07-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0034_rename_supportticket_ticket_supportfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('closed', 'Closed')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
