# Generated by Django 4.2.2 on 2023-07-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0036_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('answered', 'Answered'), ('closed', 'Closed')], max_length=200, null=True),
        ),
    ]
