# Generated by Django 4.2.2 on 2023-07-24 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0040_ticketreply_replied_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('types', models.CharField(blank=True, choices=[('transaction', 'transaction'), ('kyc', 'kyc'), ('user', 'user'), ('ticket', 'ticket')], max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ids', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('types', models.CharField(blank=True, choices=[('transaction', 'transaction'), ('kyc', 'kyc'), ('ticket', 'ticket')], max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ids', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notification', to='homepage.customer')),
            ],
        ),
    ]
