# Generated by Django 4.2.2 on 2023-07-25 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0045_sendingpurpose_sourcefund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sending_purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_purpose', to='homepage.sendingpurpose'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_of_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_source', to='homepage.sourcefund'),
        ),
    ]
