# Generated by Django 4.2.2 on 2023-07-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0049_defaultcurrencyadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_amount', models.IntegerField()),
                ('maximum_amount', models.IntegerField()),
                ('daily_transfer_remit', models.IntegerField()),
                ('maximum_cap_charge', models.IntegerField()),
            ],
        ),
    ]
