# Generated by Django 4.2.2 on 2023-07-26 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0051_alter_transaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=300)),
                ('account_number', models.CharField(max_length=500)),
                ('bank_name', models.CharField(max_length=200)),
                ('swift_code', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_country_bank', to='homepage.country')),
            ],
        ),
    ]
