# Generated by Django 4.2.2 on 2023-07-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0055_remove_kyc_zip_code_kyc_licence_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='document_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='document/'),
        ),
    ]
