# Generated by Django 4.2.2 on 2023-07-29 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0063_alter_transaction_commision_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='commision_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currency',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currency',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_country', to='homepage.country'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currecy_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
