# Generated by Django 4.2.2 on 2023-07-30 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0068_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_screenshot', to='homepage.transaction'),
        ),
    ]
