# Generated by Django 4.2.2 on 2023-08-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0071_alter_otpcode_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_image'),
        ),
    ]
