# Generated by Django 4.2.2 on 2023-08-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0075_adminbankaccount_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='document_type',
            field=models.CharField(choices=[('National ID', 'National ID'), ('Driver licence', 'Driver licence'), ('Passport', 'Passport')], max_length=200),
        ),
    ]
