# Generated by Django 4.2.2 on 2023-08-06 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0076_alter_kyc_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionnote',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_note', to='homepage.transaction'),
        ),
    ]
